apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deploy
  labels:
    app: mongo-db 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db 
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
          - containerPort: 27017 
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: root_username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: root_password  



---


apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
spec:
  selector:
    app: mongo-db 
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017